name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2


profile: 'ecommerce_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  start_date: '2023-01-01'
  lookback_days: 30
  env_name: 'dev'

models:
  ecommerce_analytics:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

seeds:
  ecommerce_analytics:
    +schema: raw
    +quote_columns: false

snapshots:
  ecommerce_analytics:
    +target_schema: snapshots